#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(PROJECT_ROOT, 'skills');

const SKILL_MATRIX = [
  { category: 'web-dev/react', sub: 'react', topics: ['hooks-optimization','server-components','state-architecture','testing-library','performance','suspense-patterns','error-boundaries','custom-hooks','concurrent-features','form-handling','routing-patterns','ssr-patterns','code-splitting','lazy-loading','context-patterns','redux-toolkit','zustand','jotai','tanstack-query','websocket-realtime','animation-framer','accessibility-a11y','typescript-patterns','design-system','component-composition','memoization','ref-patterns','portal-patterns','compound-components','render-props'] },
  { category: 'web-dev/vue', sub: 'vue', topics: ['composition-api','pinia-store','nuxt3-ssr','reactivity-system','component-patterns','performance-optim','form-validation','testing-vitest','typescript-vue','custom-directives','plugins','provide-inject','teleport','suspense','transition-animation','vuex-migration','props-emits','slots-patterns','composables','mixin-alternatives','i18n','pwa-vue','testing-cypress','deploy-patterns'] },
  { category: 'web-dev/nextjs', sub: 'nextjs', topics: ['app-router','server-components','caching-strategies','middleware','api-routes','streaming-ssr','parallel-routes','intercepting-routes','loading-ui','error-handling','seo-optimization','image-optimization','font-optimization','script-optimization','metadata-api','route-handlers','server-actions','data-fetching','incremental-static','edge-runtime','layout-patterns','template-patterns','deployment','testing','performance'] },
  { category: 'web-dev/svelte', sub: 'svelte', topics: ['runes-reactivity','sveltekit-routing','ssr-patterns','stores-advanced','component-lifecycle','actions','transitions','animations','svelte-5','typescript','testing','deployment','form-actions','load-functions','hooks','adapter-patterns','seo','performance','state-management'] },
  { category: 'web-dev/angular', sub: 'angular', topics: ['signals-state','standalone-components','rxjs-operators','dependency-injection','ngrx-state','testing-jasmine','performance-optim','route-guards','interceptors','form-handling','custom-pipes','directives','lazy-loading-modules','server-side-rendering','service-workers','pwa-patterns','i18n','aot-compilation','change-detection','zoneless'] },
  { category: 'web-dev/astro', sub: 'astro', topics: ['islands-architecture','content-collections','ssg-patterns','ssr-hybrid','integrations','components','layouts','data-fetching','markdown-mdx','view-transitions','performance','deployment','testing','seo','images','scripts'] },
  { category: 'web-dev/remix', sub: 'remix', topics: ['loaders-actions','optimistic-ui','progressive-enhancement','nested-routing','error-boundaries','form-handling','caching-headers','session-management','meta-api','resource-routes','streaming','deferring','prefetching','deployment','testing','typescript'] },
  { category: 'backend/nodejs', sub: 'nodejs', topics: ['event-loop-mastery','streams-pipeline','cluster-scaling','worker-threads','process-management','express-production','fastify-performance','nestjs-architecture','rest-api-design','graphql-server','websocket-server','file-upload','rate-limiting','caching-redis','queue-bull','cron-jobs','logging-winston','health-checks','graceful-shutdown','error-handling','validation-joi','authentication-jwt','authorization-rbac','database-orm','transaction-patterns','connection-pooling','middleware-patterns','testing-jest','docker-deployment','serverless-functions','microservices-node','event-driven','message-broker','api-versioning','cors-security'] },
  { category: 'backend/python', sub: 'python', topics: ['fastapi-production','django-architecture','flask-patterns','async-await','celery-tasks','pydantic-validation','sqlalchemy-orm','alembic-migrations','testing-pytest','type-hints-mypy','poetry-packaging','docker-python','gunicorn-uvicorn','rest-api','graphql-strawberry','websockets','caching-patterns','auth-oauth','rate-limiting','background-jobs','database-patterns','error-handling','logging-structlog','monitoring-opentelemetry','testing-mock','property-based-testing','data-validation','settings-management','secrets-management','api-versioning'] },
  { category: 'backend/rust', sub: 'rust', topics: ['async-tokio','ownership-patterns','lifetime-mastery','axum-server','error-handling-thiserror','serde-serialization','sqlx-database','redis-client','grpc-tonic','cli-clap','testing-patterns','performance-zero-copy','concurrency-threads','channel-patterns','trait-design','pattern-matching','macro-system','ffi-bindings','wasm-compilation','embedded-patterns','build-system','cross-compilation','memory-safety','type-state','phantom-types','unsafe-guide'] },
  { category: 'backend/go', sub: 'go', topics: ['goroutines-channels','context-patterns','http-server','grpc-production','database-sql','testing-tables','error-handling','concurrency-patterns','middleware-chain','cli-cobra','docker-go','kubernetes-client','rest-api','websocket-realtime','message-queue','caching-patterns','auth-jwt','rate-limiting','observability','performance-profiling','generics-patterns','interface-design','dependency-injection','build-tags'] },
  { category: 'backend/java', sub: 'java', topics: ['spring-boot-3','virtual-threads','reactive-webflux','jpa-hibernate','testing-junit5','record-patterns','sealed-classes','pattern-matching','graalvm-native','micrometer-observability','security-spring','caching-redis','messaging-kafka','graphql-dgs','rest-api','websocket','docker-java','kubernetes-deploy','performance-jvm','concurrency-structured','optional-patterns','stream-advanced','data-validation','api-versioning','migration-flyway'] },
  { category: 'backend/csharp', sub: 'csharp', topics: ['aspnet-minimal-api','blazor-wasm','entity-framework','mediatr-cqrs','testing-xunit','background-services','dependency-injection','middleware-pipeline','auth-identity','signalr-realtime','graphql-hotchocolate','docker-deploy','performance-span','async-patterns','linq-mastery','record-types','pattern-matching','source-generators','minimal-apis','openapi-swagger','health-checks','configuration-patterns'] },
  { category: 'ai-ml/llm', sub: 'llm', topics: ['prompt-engineering','fine-tuning-lora','rlhf-training','evaluation-metrics','hallucination-prevention','chain-of-thought','few-shot-patterns','token-optimization','model-selection','inference-optimization','streaming-responses','function-calling','structured-output','cost-optimization','caching-strategies','fallback-patterns','guardrails-output','red-teaming','bias-detection','model-compression','quantization','distillation','inference-serving','batch-processing','context-window','long-context','embedding-patterns','tokenizer-internals'] },
  { category: 'ai-ml/rag', sub: 'rag', topics: ['chunking-strategies','hybrid-search','reranking-crossencoder','embedding-models','vector-indexing','ragas-evaluation','query-transformation','hyde-patterns','parent-document','sentence-window','metadata-filtering','multi-modal-rag','agentic-rag','graph-rag','streaming-rag','caching-rag','evaluation-framework','production-deployment','cost-optimization','failure-modes'] },
  { category: 'ai-ml/agents', sub: 'agents', topics: ['langgraph-orchestration','tool-design','memory-systems','planning-decomposition','multi-agent','supervisor-pattern','evaluation-agents','human-in-loop','retry-patterns','agent-safety','autonomous-agents','coding-agents','research-agents','data-analysis-agents','customer-support-agents','workflow-automation','state-management','error-recovery','observability-agents','production-patterns'] },
  { category: 'ai-ml/computer-vision', sub: 'computer-vision', topics: ['pytorch-training','yolo-detection','image-segmentation','object-tracking','face-detection','ocr-text','video-analysis','augmentation','transfer-learning','model-quantization-cv','edge-deployment','data-pipeline-cv','annotation-tools','evaluation-metrics-cv','model-serving-cv','real-time-inference','3d-vision','generative-vision','diffusion-models','gan-patterns'] },
  { category: 'ai-ml/mlops', sub: 'mlops', topics: ['mlflow-tracking','model-registry','feature-store','data-versioning','experiment-tracking','model-monitoring','drift-detection','a-b-testing-ml','pipeline-automation','ci-cd-ml','model-serving-patterns','batch-inference','real-time-inference-mlops','cost-optimization-ml','gpu-management','distributed-training','hyperparameter-tuning','auto-scaling-ml','debugging-ml','compliance-ml'] },
  { category: 'cloud/aws', sub: 'aws', topics: ['lambda-optimization','api-gateway-patterns','dynamodb-design','s3-patterns','sqs-sns-eventbridge','step-functions','ecs-fargate','ec2-autoscaling','rds-aurora','cloudfront-cdn','cognito-auth','iam-security','vpc-networking','cloudformation-cdk','cost-optimization','monitoring-cloudwatch','logging-patterns','secrets-management','disaster-recovery','multi-region','serverless-patterns','container-patterns','database-migration','event-driven','batch-processing','streaming-kinesis','iot-patterns','ml-sagemaker','analytics-athena','security-hardening','compliance','well-architected'] },
  { category: 'cloud/gcp', sub: 'gcp', topics: ['cloud-run','bigquery-analytics','gke-kubernetes','pub-sub-messaging','cloud-functions','firestore-design','cloud-sql','storage-gcs','vertex-ai','dataflow-pipeline','monitoring-ops','iam-gcp','networking-vpc','terraform-gcp','cost-gcp','security-gcp','apigee-patterns','composer-airflow','alloydb','bigtable-patterns'] },
  { category: 'cloud/azure', sub: 'azure', topics: ['functions-serverless','aks-kubernetes','cosmos-db','service-bus','app-service','blob-storage','azure-ad','devops-pipelines','monitor-azure','virtual-machines','sql-database','event-grid','logic-apps','key-vault','cdn-frontdoor','api-management','container-apps','databricks','cognitive-services'] },
  { category: 'devops/docker', sub: 'docker', topics: ['multi-stage-builds','dockerfile-best-practices','compose-production','networking-docker','volumes-storage','security-hardening-docker','image-optimization','registry-management','swarm-orchestration','health-checks-docker','logging-docker','monitoring-docker','ci-cd-docker','debugging-containers','windows-containers','rootless-docker','buildkit-advanced','testing-docker','resource-limits','caching-layers'] },
  { category: 'devops/kubernetes', sub: 'kubernetes', topics: ['pod-design','deployment-strategies','service-mesh','rbac-security','network-policies','helm-charts','operators-pattern','autoscaling-hpa-vpa','storage-pv','secret-management','monitoring-prometheus','logging-efk','ci-cd-k8s','troubleshooting','disaster-recovery-k8s','multi-cluster','gitops-argocd','admission-controllers','resource-quotas','pod-security','ingress-advanced','jobs-cronjobs','config-management','custom-resources'] },
  { category: 'devops/cicd', sub: 'cicd', topics: ['github-actions','gitlab-ci','jenkins-pipeline','argocd-gitops','progressive-delivery','feature-flags','artifact-management','testing-automation','security-scanning','deployment-strategies','rollback-patterns','environment-management','secret-management-ci','pipeline-optimization','notification-alerts','compliance-automation','infra-as-code-ci','container-ci','mobile-ci','monorepo-ci'] },
  { category: 'devops/terraform', sub: 'terraform', topics: ['module-design','state-management','workspace-patterns','drift-detection','testing-terratest','security-checkov','cost-estimation','multi-cloud','import-existing','migration-refactoring','variable-patterns','output-patterns','dynamic-blocks','provisioners','provider-development','remote-execution','policy-sentinel','documentation-tf','pipeline-integration'] },
  { category: 'devops/monitoring', sub: 'monitoring', topics: ['prometheus-metrics','grafana-dashboards','opentelemetry-tracing','alerting-rules','slo-sli-design','log-aggregation','distributed-tracing','error-tracking','performance-monitoring','capacity-planning','incident-management','runbook-automation','anomaly-detection','synthetic-monitoring','real-user-monitoring','cost-monitoring','security-monitoring','chaos-engineering','load-testing','benchmarking'] },
  { category: 'database/sql', sub: 'sql', topics: ['postgresql-performance','mysql-optimization','query-optimization','indexing-strategies','explain-analyze','partitioning','replication','connection-pooling','migration-patterns','backup-recovery','monitoring-sql','security-hardening-sql','json-sql','window-functions','cte-advanced','transaction-isolation','deadlock-prevention','full-text-search','temporal-tables','upsert-patterns'] },
  { category: 'database/nosql', sub: 'nosql', topics: ['mongodb-aggregation','redis-patterns','cassandra-modeling','dynamodb-advanced','elasticsearch-query','neo4j-graph','couchdb-patterns','modeling-patterns','consistency-tuning','sharding-rebalancing','caching-advanced','time-series-nosql','event-sourcing-nosql','migration-nosql','monitoring-nosql'] },
  { category: 'database/vector', sub: 'vector', topics: ['pinecone-patterns','weaviate-schema','qdrant-filtering','milvus-scaling','embedding-strategies','index-selection','hybrid-search-vec','reranking-vec','chunking-vec','metadata-filtering','multi-tenant-vec','cost-optimization-vec','evaluation-vec','production-deploy-vec','monitoring-vec','migration-vec','benchmarking-vec','fine-tuning-embeddings','domain-specific-vec','streaming-ingestion'] },
  { category: 'mobile/react-native', sub: 'react-native', topics: ['performance-optimization','navigation-deep-linking','native-modules','push-notifications','offline-first','testing-detox','animation-reanimated','state-management-rn','app-security','ci-cd-mobile','app-store-deployment','accessibility-rn','typescript-rn','expo-advanced','background-tasks','biometric-auth','camera-media','location-services','analytics-rn'] },
  { category: 'mobile/flutter', sub: 'flutter', topics: ['state-riverpod','animations-implicit','animations-explicit','platform-channels','testing-flutter','performance-flutter','offline-sync','push-notifications-fl','security-flutter','ci-cd-flutter','app-store-fl','accessibility-fl','internationalization','responsive-design','custom-paint','isolates-compute','firebase-integration','rest-api-fl','local-storage'] },
  { category: 'mobile/swift', sub: 'swift', topics: ['swiftui-advanced','combine-reactive','core-data','async-await-swift','testing-xctest','uikit-modern','concurrency-swift','memory-management','networking-alamofire','push-notifications-sw','accessibility-sw','ci-cd-swift','app-store-sw','security-swift','core-ml','arkit-visions','widget-kit','app-clips','swift-data'] },
  { category: 'mobile/kotlin', sub: 'kotlin', topics: ['compose-ui','coroutines-flow','architecture-mvi','testing-mockk','hilt-di','room-database','retrofit-networking','navigation-compose','workmanager','push-notifications-kt','security-kt','ci-cd-kt','app-store-kt','accessibility-kt','performance-kt','gradle-advanced','kotlin-multiplatform','serialization','coroutines-advanced'] },
  { category: 'game-dev/unity', sub: 'unity', topics: ['csharp-patterns','ecs-dots','shader-graph','vfx-graph','physics-advanced','networking-netcode','animation-statemachine','ui-toolkit','addressables','performance-profiling','mobile-optimization','scriptable-objects','editor-tooling','terrain-systems','navmesh-ai','audio-systems','cinemachine-camera','post-processing','2d-systems','testing-unity','deployment'] },
  { category: 'game-dev/godot', sub: 'godot', topics: ['gdscript-advanced','signals-architecture','tilemap-systems','shader-gdshader','physics-godot','networking-multiplayer','animation-tree','ui-theming','audio-godot','performance-godot','3d-lighting','2d-platformer','state-machine','dialogue-system','inventory-system','save-load','procedural-gen','testing-godot','deployment-godot','exporting'] },
  { category: 'game-dev/unreal', sub: 'unreal', topics: ['blueprints-advanced','cpp-gameplay','ai-behavior-trees','umg-ui','material-editor','niagara-vfx','networking-replication','animation-bp','physics-chaos','optimization-lumen','nanite-mesh','world-partition','audio-meta','sequencer-cinematic','procedural-gen-ue','testing-automation','packaging-deploy','gas-ability-system','landscape-terrain','plugins-development'] },
  { category: 'security/owasp', sub: 'owasp', topics: ['injection-prevention','xss-prevention','csrf-protection','auth-failures','misconfig-fixes','sensitive-exposure','access-control','security-headers','deserialization','ssrf-prevention','logging-monitoring-sec','session-management','file-upload-security','api-security','dependency-vulnerabilities','container-security','cloud-security','mobile-security'] },
  { category: 'security/auth', sub: 'auth', topics: ['jwt-best-practices','oauth2-oidc','session-management-auth','password-hashing','mfa-implementation','sso-saml','zero-trust','rbac-abac','token-rotation','api-key-management','credential-stuffing','brute-force-protection','account-recovery','social-login','device-auth','step-up-auth','continuous-auth','biometric-auth'] },
  { category: 'security/cryptography', sub: 'cryptography', topics: ['encryption-rest','encryption-transit','key-management','tls-configuration','digital-signatures','hashing-patterns','random-generation','certificate-management','hsm-patterns','secret-sharing','homomorphic','post-quantum','password-storage','audit-logging-crypto','compliance-crypto'] },
  { category: 'testing/unit', sub: 'unit', topics: ['test-structure','mocking-patterns','property-based-testing','mutation-testing','coverage-strategies','test-pyramid','snapshot-testing','parameterized-tests','async-testing','dependency-injection-test','time-dependent-testing','database-testing','api-testing','integration-boundaries','test-doubles','bdd-tdd','approval-testing','contract-testing'] },
  { category: 'testing/e2e', sub: 'e2e', topics: ['playwright-patterns','cypress-advanced','test-strategy','visual-regression','accessibility-testing-e2e','performance-testing-e2e','parallel-execution','ci-cd-testing','page-objects','test-data-management','cross-browser','mobile-testing-e2e','api-e2e','monitoring-e2e','flaky-tests'] },
  { category: 'architecture/microservices', sub: 'microservices', topics: ['service-mesh','circuit-breaker','saga-pattern','api-gateway','event-sourcing','cqrs-pattern','distributed-tracing-arch','consensus-pattern','sidecar-pattern','strangler-fig','backend-for-frontend','anti-corruption-layer','deployment-patterns-arch','observability-arch','testing-microservices','data-consistency','event-storming','domain-events','outbox-pattern','idempotency'] },
  { category: 'architecture/ddd', sub: 'ddd', topics: ['aggregates','bounded-contexts','value-objects','domain-events-ddd','repositories','domain-services','application-services','specification-pattern','factory-pattern-ddd','context-mapping','ubiquitous-language','event-storming-ddd','hexagonal-architecture','cqrs-ddd','testing-ddd','migration-ddd'] },
  { category: 'architecture/event-driven', sub: 'event-driven', topics: ['event-sourcing-ed','cqrs-event','saga-orchestration','choreography-vs-orchestration','event-schema','schema-registry','compensation-pattern','exactly-once','ordering-guarantees','dead-letter','idempotency-ed','testing-event','monitoring-event','scaling-event','migration-event'] },
  { category: 'design-patterns/creational', sub: 'creational', topics: ['singleton-safe','factory-method','abstract-factory','builder-advanced','prototype-pattern','dependency-injection-dp','object-pool','lazy-initialization','multiton','service-locator'] },
  { category: 'design-patterns/structural', sub: 'structural', topics: ['adapter-pattern','bridge-pattern','composite-pattern','decorator-advanced','facade-pattern','flyweight-pattern','proxy-pattern','decorator-compose','module-pattern','extension-pattern'] },
  { category: 'design-patterns/behavioral', sub: 'behavioral', topics: ['chain-of-responsibility','command-pattern','iterator-advanced','mediator-pattern','memento-pattern','observer-pattern','state-pattern','strategy-pattern','template-method','visitor-pattern','null-object','specification-bh'] },
  { category: 'blockchain/evm', sub: 'blockchain', topics: ['solidity-advanced','smart-contract-security','gas-optimization','erc-standards','defi-patterns','nft-patterns','dao-governance','layer2-scaling','cross-chain','testing-foundry','deployment-contracts','upgrade-patterns','oracle-integration','tokenomics','wallet-integration','event-indexing','frontend-web3','dex-mechanics','lending-protocols','yield-strategies'] },
  { category: 'data-science/analysis', sub: 'data-science', topics: ['pandas-mastery','numpy-vectorization','visualization-seaborn','statistical-modeling','feature-engineering','model-selection','cross-validation','ensemble-methods','time-series-forecast','anomaly-detection','clustering-advanced','nlp-fundamentals','recommendation-systems','a-b-testing-ds','data-cleaning','pipeline-automation-ds','experiment-tracking-ds','production-model','interpretability','fairness-bias'] },
  { category: 'performance/optimization', sub: 'performance', topics: ['profiling-techniques','benchmarking-patterns','memory-optimization','cpu-optimization','io-optimization','network-optimization','caching-strategies-perf','lazy-loading-perf','pagination-optimization','batch-processing-perf','compression-patterns','cdn-optimization','database-query-optim','async-performance','worker-threads-perf','monitoring-perf','load-testing-perf','web-performance','api-performance','mobile-performance'] },
  { category: 'accessibility/a11y', sub: 'accessibility', topics: ['wcag-compliance','aria-patterns','screen-reader-testing','keyboard-navigation','color-contrast','form-accessibility','media-accessibility','mobile-accessibility','testing-accessibility','documentation-accessibility','inclusive-design','cognitive-accessibility','motor-accessibility','visual-accessibility','auditory-accessibility'] },
  { category: 'apis/design', sub: 'apis', topics: ['rest-design','graphql-schema','grpc-streaming','api-versioning','rate-limiting-api','pagination-api','filtering-sorting','error-handling-api','authentication-api','authorization-api','caching-api','documentation-openapi','testing-api','security-api','pagination-cursor','hateoas-patterns','webhook-patterns','event-api','streaming-api','sdk-design'] },
  { category: 'devex/tooling', sub: 'devex', topics: ['developer-portal','documentation-system','code-review-guide','onboarding-automation','templates-scaffolding','local-development','debugging-guide','logging-standards','error-catalog','runbook-template','architecture-decision','tech-radar','metrics-dashboard','feedback-loops','developer-survey'] },
];

const DIFFICULTIES = ['beginner', 'intermediate', 'advanced', 'expert'];

const PATTERNS = ['architecture', 'best-practices', 'patterns', 'optimization', 'production', 'security', 'testing', 'migration', 'troubleshooting', 'advanced', 'fundamentals', 'deep-dive', 'implementation', 'integration', 'deployment', 'monitoring', 'design', 'scalability', 'performance', 'hardening'];

function getDifficultyInstructions(difficulty) {
  const map = {
    beginner: `## Role\nYou are a patient mentor teaching this technology. Focus on fundamentals with clear examples.\n\n## Core Competencies\nExplain concepts step by step. Use simple, runnable code examples. Point out common beginner mistakes.`,
    intermediate: `## Role\nYou are an experienced developer with production experience in this technology.\n\n## Core Competencies\nProvide practical patterns with trade-off analysis. Show before/after code examples. Cover error handling and edge cases.`,
    advanced: `## Role\nYou are a senior engineer who has built and scaled systems using this technology in production.\n\n## Core Competencies\nDeep-dive into internals, performance characteristics, and advanced patterns. Provide production-grade code with monitoring, error handling, and optimization.`,
    expert: `## Role\nYou are a recognized expert who has contributed to this technology's ecosystem and operated it at massive scale.\n\n## Core Competencies\nCover internals, edge cases, failure modes, and cutting-edge patterns. Provide battle-tested code with observability, resilience, and cost optimization. Challenge conventional wisdom when warranted.`,
  };
  return map[difficulty] || map.intermediate;
}

function getAntiPatterns(topic, difficulty) {
  return `## Anti-Patterns\n- Over-engineering simple problems with complex patterns\n- Ignoring error handling and edge cases\n- Not measuring performance before optimizing\n- Skipping tests for critical paths\n- Hardcoding configuration values\n- Not considering security implications\n- Copying patterns without understanding trade-offs\n- Not planning for observability and debugging`;
}

function generateSkillContent(skill) {
  const { sub, topic, pattern, difficulty } = skill;
  const title = `${sub}-${topic}-${pattern}`;
  const header = `---\nname: ${title}\ncategory: ${skill.category}\nversion: 1.0.0\ndifficulty: ${difficulty}\ntags: ["${sub}","${topic}","${pattern}","${difficulty}"]\ntools: ["claude-code","kilo","cline","opencode","cursor","windsurf"]\ndescription: "${sub} ${topic} ${pattern} at ${difficulty} level"\n---\n`;
  const body = `# ${sub.charAt(0).toUpperCase() + sub.slice(1)} ${topic.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} — ${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}\n\n${getDifficultyInstructions(difficulty)}\n\n### ${topic.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} — ${pattern}\n\nThis skill covers ${pattern} patterns for ${topic} in ${sub}.\n\n#### Key Principles\n- Always start with the simplest solution that works\n- Measure before optimizing\n- Handle errors gracefully at every layer\n- Write tests for critical paths\n- Document why, not what\n\n#### Code Example\n\n\`\`\`\n// ${sub} ${topic} ${pattern} pattern\n// Adapt this to your specific ${sub} project's conventions\n// This is a reference implementation — modify for your use case\n\`\`\`\n\n${getAntiPatterns(topic, difficulty)}\n`;
  return header + body;
}

function generateSkills(targetCount = 50000, preview = false) {
  let count = 0;
  const total = preview ? Math.min(targetCount, 20) : targetCount;

  for (const matrix of SKILL_MATRIX) {
    for (const topic of matrix.topics) {
      for (const pattern of PATTERNS) {
        for (const difficulty of DIFFICULTIES) {
          if (count >= total) {
            console.log(`Generated ${count} skills.`);
            return count;
          }

          const skill = { ...matrix, topic, pattern, difficulty };
          const content = generateSkillContent(skill);
          const fileName = `${skill.sub}-${topic}-${pattern}-${difficulty}.md`;
          const dir = path.join(SKILLS_DIR, matrix.category);

          fs.mkdirSync(dir, { recursive: true });
          fs.writeFileSync(path.join(dir, fileName), content);
          count++;

          if (count % 5000 === 0) {
            console.log(`Generated ${count} / ${total} skills...`);
          }
        }
      }
    }
  }

  console.log(`Done! Generated ${count} unique skills.`);
  return count;
}

const target = parseInt(process.argv[2]) || 50000;
const isPreview = process.argv.includes('--preview');
generateSkills(target, isPreview);
